services:
  database:
    container_name: iotbay-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=iotbayuser
      - POSTGRES_PASSWORD=SupaStrongPassword
      - POSTGRES_DB=iotbaydb
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
