DROP TABLE IF EXISTS orders_products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS payment_details;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS payment_details;
DROP TABLE IF EXISTS card_payemnt;
DROP TABLE IF EXISTS user_credentials;
DROP TABLE IF EXISTS roles;
